"""payout_one_primary_per_user

Revision ID: 085858a073f0
Revises: e313ebafea30
Create Date: 2026-04-19 22:40:00.757044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '085858a073f0'
down_revision: Union[str, Sequence[str], None] = 'e313ebafea30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_payouts_user_one_primary', 'payouts', ['user_id'], unique=True, postgresql_where=sa.text('is_primary IS TRUE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_payouts_user_one_primary', table_name='payouts', postgresql_where=sa.text('is_primary IS TRUE'))
    # ### end Alembic commands ###
