"""events tier_details json

Revision ID: 2be85f88de5a
Revises: 4024501e9cfb
Create Date: 2026-04-09 10:10:15.634446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2be85f88de5a'
down_revision: Union[str, Sequence[str], None] = '4024501e9cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('tier_details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'tier_details')
    # ### end Alembic commands ###
