"""add whatsapp_notifications_enabled to profiles

Revision ID: 4024501e9cfb
Revises: d2452aa00da5
Create Date: 2026-04-07 17:10:59.968239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4024501e9cfb'
down_revision: Union[str, Sequence[str], None] = 'd2452aa00da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('whatsapp_notifications_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'whatsapp_notifications_enabled')
    # ### end Alembic commands ###
