"""payments_razorpay_columns

Revision ID: 458750b79de0
Revises: 62574400d2d5
Create Date: 2026-04-18 12:42:51.791045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '458750b79de0'
down_revision: Union[str, Sequence[str], None] = '62574400d2d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('razorpay_order_id', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'razorpay_payment_id')
    op.drop_column('payments', 'razorpay_order_id')
    # ### end Alembic commands ###
