"""events_amenities_json

Revision ID: 62574400d2d5
Revises: 7b005bc51580
Create Date: 2026-04-16 16:40:50.386659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62574400d2d5'
down_revision: Union[str, Sequence[str], None] = '7b005bc51580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('amenities', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'amenities')
    # ### end Alembic commands ###
