"""add users account status

Revision ID: 7b005bc51580
Revises: 2be85f88de5a
Create Date: 2026-04-13 16:53:26.104670

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7b005bc51580"
down_revision: Union[str, Sequence[str], None] = "2be85f88de5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "deleted",
                "blocked",
                name="accountstatus",
                native_enum=False,
                length=32,
            ),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "status")
    # ### end Alembic commands ###
