"""devices_device_key_slim_columns

Revision ID: d2452aa00da5
Revises: g1h2i3j4k5l6
Create Date: 2026-04-06 22:53:46.149684

Autogenerated then adjusted: backfill `device_key` before NOT NULL; do not touch `users` indexes.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "d2452aa00da5"
down_revision: Union[str, Sequence[str], None] = "g1h2i3j4k5l6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_key', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_devices_device_key'), 'devices', ['device_key'], unique=True)
    op.drop_column('devices', 'app_version')
    op.drop_column('devices', 'is_current_device')
    op.drop_column('devices', 'ip_address')
    op.drop_column('devices', 'os')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.add_column(
        "devices",
        sa.Column("app_version", sa.String(length=64), server_default="", nullable=False),
    )
    op.add_column("devices", sa.Column("os", sa.String(length=128), nullable=True))
    op.add_column(
        "devices",
        sa.Column(
            "is_current_device",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column("devices", sa.Column("ip_address", sa.String(length=64), nullable=True))

    op.drop_index(op.f("ix_devices_device_key"), table_name="devices")
    op.drop_column("devices", "device_key")

    op.alter_column("devices", "app_version", server_default=None)
    op.alter_column("devices", "is_current_device", server_default=None)
